In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r"C:\Users\91790\Downloads\insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [22]:
x = df.drop("charges", axis=1)
x

      age     sex     bmi  children smoker     region
0      19  female  27.900         0    yes  southwest
1      18    male  33.770         1     no  southeast
2      28    male  33.000         3     no  southeast
3      33    male  22.705         0     no  northwest
4      32    male  28.880         0     no  northwest
...   ...     ...     ...       ...    ...        ...
1333   50    male  30.970         3     no  northwest
1334   18  female  31.920         0     no  northeast
1335   18  female  36.850         0     no  southeast
1336   21  female  25.800         0     no  southwest
1337   61  female  29.070         0    yes  northwest

[1338 rows x 6 columns]

In [28]:
y = df["charges"]
y
x = pd.get_dummies(x, drop_first=True)

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [33]:
x_train, x_test, y_train, y_test = train_test_split(x , y, test_size=0.2, random_state=42)

In [34]:
model = LinearRegression()

In [35]:
model.fit(x_train, y_train)

LinearRegression()

In [37]:
y_pred = model.predict(x_test)
y_pred

array([ 8967.88297872,  7065.2166805 , 36856.63798704,  9450.2721877 ,
       26971.79346912, 10863.89692552,   166.93560551, 16901.76895802,
        1093.14137279, 11213.77983566, 28101.50726436,  9373.92348844,
        5262.03095126, 38414.94860012, 40258.40529963, 37098.52593551,
       15237.73878309, 35912.60205492,  9112.00362272, 31459.66629094,
        3844.39683361, 10129.81874751,  2372.02170879,  7139.06142266,
       11295.45944713, 12961.78032991, 14509.72096104,  6152.8865948 ,
        9962.1278757 ,  2179.42724763,  9111.84497378, 13070.50199389,
        4561.2881921 ,  3402.06687234,  4460.4031855 , 13033.25042683,
        1978.9328448 ,  8812.45868368, 33268.37273479, 32586.90421258,
        3903.15943269,  4322.883893  , 14141.8347035 , 11422.61338836,
        8773.46048028, 12098.8190718 ,  5275.2586384 ,  3147.58866547,
       35493.79149212,  9149.18503165, 15837.16425616,  2344.12229282,
       12359.38928318,  1483.90992863, 13391.17404665, 12573.30119402,
        4343.77821176, 32160.79821532, 13321.69194774, 12896.88071476,
       14168.56459793, 10503.05136734, 16359.54723073,  7758.72827274,
       11839.46940823,  4056.71495062, 26650.83725851, 10929.53388596,
        2133.1247718 ,  6209.86194091, 10729.97843556, 11626.1195939 ,
       10981.24738551,  9166.22832976, 11954.7550251 ,  6748.03949548,
        7246.61197752, 10732.43044044,  6578.45361587,  8759.3839056 ,
        3768.50512773, 36635.95341103,  6375.96917721, 30839.91362616,
       34846.25863227, 35280.86091804,  7017.9355052 , 12859.88975491,
        9936.71729532, 14472.0659404 , 17691.10490558, 35260.48563436,
       33029.85184051,  6185.55101217, 32001.26697595,  9481.01510134,
       29445.82019638,  3674.06989208, 28302.71436188,  5821.59934565,
        5403.14141551,  1883.27792343, 11500.99669519, 15074.55396976,
       11702.42281251,  4308.92472429,  9895.14543089, 31712.35732809,
         -84.89887386, 32820.62596934,  3281.96451582, 10183.30357281,
       14317.92267329, 31641.87623853, 11460.65419859,  3929.45883569,
       13110.28248132, 31810.20895133,  8150.00660583,  3235.18928592,
        8438.10357617, 10590.55072302, 15217.16790215,  5649.14984828,
        3776.54906793, 10223.13264526, 10898.95800144, 11123.70914055,
       14438.45220748,  7431.09711553,  5386.39919079,  9229.72236592,
        9341.30952498, 12537.76632437,  8337.6127997 , 15334.17127456,
        8412.47430418, 31800.18811628, 35782.76122713, 31604.47686792,
        6008.67197679, 12606.99895358,  6014.86017671, 14554.89360954,
        2495.5480534 , 32964.70342829,  6261.38956717,  5034.66492066,
       14337.89413639,  6941.89898248, 38663.97772043,  3083.9040785 ,
        5886.60164663, 31687.39604894, 11557.24342323,  8477.37391933,
       14808.89051412,  9813.86320279, 27106.14673266, 33455.23671094,
       14550.02088937,  1679.69406851, 13167.67946243,  2224.62258466,
        5447.74454218, 11568.38102191, 39808.96188799, 36498.39019946,
       34002.98372713,  3897.09203283,  7456.11424855,  8660.70529648,
       12451.75369885,  4810.93091089,  2047.645342  , 32114.50417162,
       25114.08265055, 17486.10918366, 26407.49103041, 10156.99993213,
       37261.91362745,  -441.73447032,  6777.80343241,  7780.13106085,
        4366.85962755,  5101.81057022,  5919.7030843 ,  4305.84407223,
       15189.26608134, 11130.99842156,  6930.61430177,  2525.21812248,
        1536.17284236, 31944.79733144, 16416.03571942, 12011.74555002,
        1263.47948826, 12529.51458923,  1564.72293729,  8738.08382178,
        1869.87665235, 33915.95669525, 10856.98881093,  2599.37542409,
       25674.25323054, 26344.68340698,  9429.79058034,  1794.3087412 ,
       13262.91551657,  1119.63866864, 10389.82106309, 10567.33426924,
       16940.85961864, 26849.41138226,  6939.42013463,  5192.98736857,
        5845.16463216, 13227.23711951, 11099.49169265,  8361.03611201,
        5131.22726797, 12306.07651906, 13858.6832532 , 35773.95737481,
        4154.81868927, 28920.42193423,  -913.95366854,  2871.55863391,
       11047.5082792 , 15678.34410544,  5211.7995876 ,  6886.11668561,
        3852.49077746, 31315.75188868,  7239.16485633, 12407.76184907,
        5614.99322403,  9529.94937076, 36312.24534272,  4430.78940808,
        9669.27981094, 31161.18734348,  5743.0072965 ,  4602.25022665,
        1046.61778204,  4830.63173014,  4572.83810319,  6507.91888035,
       18652.98102666, -1546.71921799,  2376.18767374, 10692.96285107,
        3151.51664438, 10210.96060745,  3728.7504636 ,  5123.75819824,
       12403.44266711,  6215.32416846,  8234.24091209,  7587.0234468 ,
        8917.57196222, 10480.6314051 , 27810.77317026, 39064.59882474,
       11758.6918436 ,  7688.41034911, 40920.42627818, 12317.6160754 ])

In [43]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("MSE: ", mse)
print("R2: ", r2)

MSE:  33598826.619092464
R2:  0.7835806689288611